name: gem-notebooks
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - myst-nb
  - notebook
  - sphinx
  - sphinx-book-theme
  - sphinx-reredirects
  - ipykernel
  - nbconvert
  - pandoc
  - pip
  - matplotlib
  - cmcrameri
  - pyvista
  - meshio
  - pandas<2.2
  - imageio
  - pip:
      - nbsphinx
